name: Internal Testing App Upload

on:
  push:
    branches: [qa]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: service_account.json
        packageName: com.ncodes.ecommerce
        releaseFiles: app/build/outputs/bundle/release/app-release.aab
        track: qa
        status: completed
        inAppUpdatePriority: 2
        userFraction: 1
#        whatsNewDirectory: distribution/whatsnew
#        mappingFile: app/build/outputs/mapping/release/mapping.txt
#        debugSymbols: app/intermediates/merged_native_libs/release/out/lib


